# Generated by Django 4.2.2 on 2023-06-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('symbol', models.CharField(blank=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('icon', models.ImageField(upload_to='currency/icons')),
                ('buy_rate', models.FloatField()),
                ('sell_rate', models.FloatField()),
            ],
        ),
    ]
