# Generated by Django 4.2.2 on 2023-06-24 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room_method', to='payment.method')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=3000, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room_for_message', to='chat.chatroom')),
                ('method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_method', to='payment.method')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoomController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_controller_name', models.CharField(blank=True, max_length=200, null=True)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controller_User', to=settings.AUTH_USER_MODEL)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controller_method', to='payment.method')),
            ],
        ),
    ]
