# Generated by Django 4.2.3 on 2023-08-03 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='method',
        ),
    ]
