# Generated by Django 4.2.3 on 2023-08-03 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('chat', '0004_remove_message_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_method', to='payment.method'),
        ),
    ]
