# Generated by Django 4.2.2 on 2023-06-24 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_details', models.TextField(blank=True, max_length=2000, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('order_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('method', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_method', to='payment.method')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
