# Generated by Django 4.2.3 on 2023-07-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bep20_address',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='purpose',
            field=models.CharField(default='pay', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='trc20_address',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
