# Generated by Django 4.2.3 on 2023-08-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='purpose',
            field=models.CharField(blank=True, default='pay', max_length=200, null=True),
        ),
    ]
