# Generated by Django 4.2.5 on 2023-10-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(default='processing', max_length=10, null=True),
        ),
    ]
